image: quantumtinkerer/research
test:
  script:
    - conda install -y -q pytest-cov
    - py.test --verbose --cov=adaptive --cov-report term --cov-report html adaptive
  artifacts:
    paths:
      - htmlcov
