trigger:
  branches:
    include:
    - master
pr:
  - "*"

jobs:
- job: pytest36
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: pip install tox
    displayName: 'Install tox'
  - script: tox -e py36
    displayName: 'Run the tests'

- job: pytest37
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: pip install tox
    displayName: 'Install tox'
  - script: tox -e py37
    displayName: 'Run the tests'
  - script: tox -e clean,report
    displayName: 'Test coverage'

- job: pre_commit
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: pip install tox
    displayName: 'Install tox'
  - script: tox -e pre-commit
    displayName: 'Lining tests'

- job: authors_check
  steps:
  - script: |
      MISSING_AUTHORS=$(git shortlog -s HEAD | sed -e "s/^[0-9\t ]*//"| xargs -i sh -c 'grep -q "{}" AUTHORS.md || echo "{} missing from authors"')
      if [ ! -z "$MISSING_AUTHORS" ]; then { echo $MISSING_AUTHORS; exit 1; }; fi
    displayName: 'Authors check'
    continueOnError: true
